
env_args:
    #env: 'TicTacToe'
    #source: 'handyrl.envs.tictactoe'
    #env: 'Geister'
    #source: 'handyrl.envs.geister'
    env: 'HungryGeese'
    source: 'handyrl.envs.kaggle.hungry_geese'


train_args:
    turn_based_training: True
    observation: False
    gamma: 0.8
    forward_steps: 16
    compress_steps: 4
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 200
    batch_size: 2
    minimum_episodes: 400
    maximum_episodes: 130000
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 4
    lambda: 0.7
    policy_target: 'VTRACE' # 'UGPO' 'VTRACE' 'TD' 'MC'
    value_target: 'VTRACE' # 'VTRACE' 'TD' 'MC'
    seed: 0
    restart_epoch: 0


worker_args:
    server_address: '95.165.139.53'
    num_parallel: 3

